# ==========================
# Namespace (optional)
# ==========================
apiVersion: v1
kind: Namespace
metadata:
  name: my-apps
---
# ==========================
# Angular Deployment
# ==========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  namespace: my-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app
          image: mohamedbelhaj/angular-app:latest
          ports:
            - containerPort: 4200

---
# Angular Service
apiVersion: v1
kind: Service
metadata: 
  name: angular-service
  namespace: my-apps
spec:
  type: NodePort
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 30080

---
# ==========================
# Django Deployment
# ==========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
  namespace: my-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
        - name: django-backend
          image: mohamedbelhaj/djangoproject:latest
          ports:
            - containerPort: 8000

---
# Django Service
apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: my-apps
spec:
  type: NodePort
  selector:
    app: django-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30081
